spring.datasource.url=jdbc:mysql://localhost:3306/PROYECTODEAULA?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Emin2006.

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080